version: '3.7'

services:
  api:
    build:
      context: ./server
      dockerfile: dockerfile
    image: cooperrunyan/api
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
  web:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: cooperrunyan/web
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
