version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: dockerfile
    image: cooperrunyan/api
    container_name: api
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 5000:5000
    environment:
      - PORT=5000
