FROM denoland/deno:ubuntu

EXPOSE 5000
WORKDIR /usr/app

RUN deno install -qAfn vr --no-check https://deno.land/x/velociraptor@1.4.0/cli.ts

COPY src/deps.ts ./src/deps.ts
RUN deno cache --unstable --no-check src/deps.ts

ADD . .
RUN deno cache --unstable --no-check src/server/server.ts

ENTRYPOINT [ "/usr/local/bin/vr" ]

CMD ["local"]